pipelines:
  default:
    - step:
        name: Sync repo
        script:
          - git remote -v
          - git remote add --mirror=fetch secondary git@github.com:mattydolan/syncssh
          - git fetch origin
          - git push secondary --all   