pipelines:
  default:
    - step:
        name: Sync repo
        script:
          - git remote add --mirror=fetch secondary https://mattdolanrva@dev.azure.com/mattdolanrva/Test/_git/syncssh
          - git fetch origin
          - git push secondary --all --force