pipelines:
  default:
    - step:
        name: Sync repo
        script:
          - git remote add --mirror=fetch secondary git@ssh.dev.azure.com:v3/mattdolanrva/Test/syncssh
          - git fetch origin
          - git push secondary --all --force